kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: dev-cluster
nodes:
  - role: control-plane
    image: kindest/node:v1.23.13
    extraPortMappings:
      - containerPort: 80
        hostPort: 5080
        protocol: TCP
      - containerPort: 443
        hostPort: 50443
        protocol: TCP

  - role: worker
    image: kindest/node:v1.23.13
